# Generated by Django 2.2.6 on 2020-09-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='vote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
