# Generated by Django 2.2.6 on 2020-09-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200825_2126'),
        ('users', '0004_auto_20200929_1215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraction',
            unique_together={('comment', 'profile')},
        ),
    ]
