# Generated by Django 2.2.6 on 2020-09-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200929_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
