# Generated by Django 2.2.6 on 2020-09-30 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_auto_20200825_2126'),
        ('users', '0006_auto_20200929_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useraction',
            unique_together={('comment', 'user')},
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='profile',
        ),
    ]
