# Generated by Django 2.2.6 on 2020-10-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200929_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='vote_type',
            field=models.CharField(blank=True, choices=[('U', 'Up'), ('D', 'Down')], max_length=20, null=True),
        ),
    ]
