# Generated by Django 2.2.6 on 2020-10-01 04:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0004_comment_vote'),
        ('users', '0008_useraction_vote_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraction',
            unique_together={('comment', 'user', 'vote_type')},
        ),
    ]
