# Generated by Django 2.2.6 on 2020-10-01 04:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20200930_2136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraction',
            unique_together={('comment', 'user')},
        ),
    ]
