# Generated by Django 2.2.6 on 2020-10-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200930_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechionPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=20, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('points', models.BigIntegerField()),
            ],
        ),
    ]
