# Generated by Django 2.2.6 on 2020-10-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_techionpoints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechionPoints',
            new_name='PointsLookup',
        ),
    ]
