# Generated by Django 2.2.6 on 2020-10-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201005_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointslookup',
            name='points',
            field=models.IntegerField(),
        ),
    ]
