# Generated by Django 2.2.6 on 2020-10-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201005_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointslookup',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
