# Generated by Django 2.2.6 on 2020-10-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_auto_20201002_1005'),
        ('users', '0014_pointslookup_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='techionprofile',
            name='paypal_account',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Techion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badges', models.CharField(blank=True, max_length=200, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('paypal_account', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='users.Profile')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='support.Question')),
            ],
        ),
    ]
