# Generated by Django 2.2.6 on 2020-10-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201005_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechionProfile',
        ),
    ]
