# Generated by Django 2.2.6 on 2020-10-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_delete_techionprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointsLookup',
        ),
    ]
