# Generated by Django 2.2.6 on 2020-10-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_delete_pointslookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techion',
            name='badges',
            field=models.CharField(blank=True, choices=[('SME', 'Teckiy SME'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=200, null=True),
        ),
    ]
