# Generated by Django 2.2.6 on 2020-10-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201005_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techion',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='techion',
            name='paypal_account',
        ),
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.CharField(blank=True, choices=[('SME', 'Teckiy SME'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='paypal_account',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='techion',
            name='vote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
