# Generated by Django 2.2.6 on 2020-10-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201005_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='techion',
            name='redeem_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='techion',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='techion',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
