# Generated by Django 2.2.6 on 2020-10-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='techion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='techion',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
