# Generated by Django 2.2.6 on 2020-10-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201018_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_preferences',
            field=models.CharField(blank=True, choices=[('active', 'Actively looking right now'), ('open', 'Open,but not actively looking'), ('inactive', 'Not interested in jobs')], max_length=200, null=True),
        ),
    ]
