# Generated by Django 2.2.6 on 2020-12-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_objectviewed_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectviewed',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='objectviewed',
            name='object_id',
        ),
    ]
