# Generated by Django 2.2.6 on 2020-12-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_post_tags'),
        ('analytics', '0003_auto_20201204_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Post'),
        ),
    ]
