# Generated by Django 2.2.6 on 2020-12-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_objectviewed_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectviewed',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Post'),
        ),
        migrations.AlterField(
            model_name='objectviewed',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Question'),
        ),
    ]
