# Generated by Django 2.2.6 on 2020-10-03 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='vote',
        ),
    ]
