# Generated by Django 2.2.6 on 2020-10-10 06:16

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20201009_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.upload_image_path),
        ),
    ]
