# Generated by Django 2.2.6 on 2020-10-12 06:06

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20201011_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=blogs.models.upload_image_path),
        ),
    ]
