# Generated by Django 2.2.6 on 2020-08-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20200811_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('P', 'Python'), ('D', 'Django'), ('S', 'SQL'), ('ORA', 'Oracle'), ('MYS', 'MYSQL'), ('JS', 'Javascript'), ('VUE', 'VueJS'), ('HTCSS', 'HTML/CSS'), ('UNI', 'Unix/Shell'), ('O', 'Other')], default='P', max_length=50),
        ),
    ]
