# Generated by Django 2.2.6 on 2020-09-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20200828_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('Q', 'Question'), ('P', 'Problem'), ('T', 'Task')], max_length=200),
        ),
    ]
