# Generated by Django 2.2.6 on 2020-09-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_questioncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('P', 'Python'), ('D', 'Django'), ('S', 'SQL'), ('ORA', 'Oracle'), ('MYS', 'MYSQL'), ('JS', 'Javascript'), ('VUE', 'VueJS'), ('HTM', 'HTML'), ('CSS', 'CSS'), ('UNI', 'Unix/Shell'), ('O', 'Other')], default='P', max_length=50),
        ),
    ]
