# Generated by Django 2.2.6 on 2020-09-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20200915_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('sql', 'SQL'), ('oracle', 'Oracle'), ('mysql', 'MYSQL'), ('javascript', 'Javascript'), ('vuejs', 'VueJS'), ('html', 'HTML'), ('css', 'CSS'), ('unix', 'Unix'), ('shellscript', 'Shell Script'), ('other', 'Other')], default='P', max_length=50),
        ),
    ]
