# Generated by Django 2.2.6 on 2020-09-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20200915_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncomment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
