# Generated by Django 2.2.6 on 2020-09-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_questioncomment_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncomment',
            options={},
        ),
    ]
