# Generated by Django 2.2.6 on 2020-09-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_auto_20200917_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'ordering': ['id']},
        ),
    ]
