# Generated by Django 2.2.6 on 2020-09-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_auto_20200917_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'ordering': ['created_date']},
        ),
    ]
