# Generated by Django 2.2.6 on 2020-09-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_businesstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('U', 'Urgent'), ('HP', 'High (pending)'), ('UP', 'Urgent (pending)')], default='L', max_length=20),
        ),
    ]
