# Generated by Django 2.2.6 on 2020-10-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='support.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('sql', 'SQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mysql', 'MYSQL'), ('javascript', 'Javascript'), ('java', 'Java'), ('vuejs', 'VueJS'), ('html', 'HTML'), ('css', 'CSS'), ('unix', 'Unix'), ('shellscript', 'Shell Script'), ('other', 'Other')], default='P', max_length=50),
        ),
    ]
