# Generated by Django 2.2.6 on 2020-10-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_auto_20201002_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=20, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('vote_count', models.IntegerField(default=0)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
