# Generated by Django 2.2.6 on 2020-10-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_pointslookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='support.Question'),
        ),
    ]
