# Generated by Django 2.2.6 on 2020-10-30 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_remove_comment_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0019_auto_20201005_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_on', models.CharField(blank=True, max_length=2000, null=True)),
                ('subject', models.CharField(blank=True, max_length=2000, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Question')),
                ('replied_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replied_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
