# Generated by Django 2.2.6 on 2020-11-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0020_replynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='replynotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
