# Generated by Django 2.2.6 on 2020-12-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecsee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecseevideo',
            name='approved',
            field=models.CharField(choices=[('Y', 'Approved'), ('N', 'Pending')], default='Y', max_length=1),
        ),
    ]
