# Generated by Django 2.2.6 on 2020-12-15 02:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecsee', '0002_tecseevideo_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecseevideo',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
