# Generated by Django 2.2.6 on 2020-12-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecsee', '0003_auto_20201214_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecseevideo',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
