# Generated by Django 2.2.6 on 2020-12-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecsee', '0004_tecseevideo_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecseevideo',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
