# Generated by Django 2.2.6 on 2021-01-02 04:14

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tecsee', '0005_auto_20201215_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecseevideo',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='tecseevideo',
            name='video',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
